### - Exercici 1

Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un pandas Dataframe. Explora les dades que conté, i queda’t únicament amb les columnes que consideris rellevants.

In [63]:
import pandas as pd
import numpy as np


csv = pd.read_csv(r'C:\Users\motxi\Documents\DelayedFlights.csv')
df = pd.DataFrame(csv)
print(df.head(), '\n')
print(df.info())  #mirem les columnes amb la info que ofereixen

   Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955
1           1  2008      1           3          4    754.0         735
2           2  2008      1           3          4    628.0         620
3           4  2008      1           3          4   1829.0        1755
4           5  2008      1           3          4   1940.0        1915

   ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled  \
0   2211.0        2225            WN  ...     4.0     8.0          0
1   1002.0        1000            WN  ...     5.0    10.0          0
2    804.0         750            WN  ...     3.0    17.0          0
3   1959.0        1925            WN  ...     3.0    10.0          0
4   2121.0        2110            WN  ...     4.0    10.0          0

   CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay  \
0                 N         0           NaN           NaN      NaN
1                 N         0           NaN           NaN      NaN
2                 N         0           NaN           NaN      NaN
3                 N         0           2.0           0.0      0.0
4                 N         0           NaN           NaN      NaN

  SecurityDelay  LateAircraftDelay
0           NaN                NaN
1           NaN                NaN
2           NaN                NaN
3           0.0               32.0
4           NaN                NaN

[5 rows x 30 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB
None

In [64]:
#Inspecciono les columnes que crec mes rellevants, a modo de taules les agrupo en 3 grans categories ; 

#-Temporals: *(Relatives al calendari i temps de vol) 
df.loc[:, ['Year','Month', 'DayofMonth', 'DayOfWeek', 'AirTime', 'ArrDelay', 'DepDelay']].head()

   Year  Month  DayofMonth  DayOfWeek  AirTime  ArrDelay  DepDelay
0  2008      1           3          4    116.0     -14.0       8.0
1  2008      1           3          4    113.0       2.0      19.0
2  2008      1           3          4     76.0      14.0       8.0
3  2008      1           3          4     77.0      34.0      34.0
4  2008      1           3          4     87.0      11.0      25.0

In [65]:
#-Causes: *(Relatives a les causes que orginen el retard)
df.loc[:, ['CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']].head()

   CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay
0           NaN           NaN       NaN            NaN                NaN
1           NaN           NaN       NaN            NaN                NaN
2           NaN           NaN       NaN            NaN                NaN
3           2.0           0.0       0.0            0.0               32.0
4           NaN           NaN       NaN            NaN                NaN

In [66]:
#-Vol: *(Miscelanea d'objectes relacionats amb el trajecte i l'aerolinia )
df.loc[:, ['UniqueCarrier', 'Origin', 'Dest', 'Distance', 'Diverted', 'Cancelled', 'CancellationCode']].head()

  UniqueCarrier Origin Dest  Distance  Diverted  Cancelled CancellationCode
0            WN    IAD  TPA       810         0          0                N
1            WN    IAD  TPA       810         0          0                N
2            WN    IND  BWI       515         0          0                N
3            WN    IND  BWI       515         0          0                N
4            WN    IND  JAX       688         0          0                N

### - Exercici 2

Fes un informe complet del data set:.

    Resumeix estadísticament les columnes d’interès
    Troba quantes dades faltants hi ha per columna
    Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)
    Taula de les aerolínies amb més endarreriments acumulats
    Quins són els vols més llargs? I els més endarrerits?
    Etc.

In [67]:
#Filtro totes les columnes que no vull per crear les noves taules. 
#Creo la taula temporals
temporals = df.filter(['Year','Month', 'DayofMonth', 'DayOfWeek', 'AirTime', 'ArrDelay', 'DepDelay'], axis=1)
#Creo la taula causes
causes = df.filter(['CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'], axis=1)
#Creo la taula vol
vol = df.filter(['UniqueCarrier', 'Origin', 'Dest', 'Distance', 'Diverted', 'Cancelled', 'CancellationCode'], axis=1)

In [68]:
#TEMPORALS
#-Les dades relatives al calendari(d/M/YY) sense combinar-se ens donen informacio a través del 
#modo. p.ex: quin es el dia_setmana/dia_mes/mes de l'any que acumula mes retards? O el temps mes 
#comú d'espera en Arribades i Sortides.
print(temporals.mode(dropna=True))

#-Airtime em dona amb els percentils una idea aproximada de la distribucio dels retards entre 
#vols llargs i vols curts.    *(combinada amb diverted/cancelled, el CancellationCode i la taula de causes, 
#p.ex em permetria comprobar la hipotesis de que un vol desviat, amb un airtime/security delay alts, 
#teòricament te probabilitats d'haver sigut segrestat  )
temporals['AirTime'].describe()
#-ArrDelay i ArrDep

   Year  Month  DayofMonth  DayOfWeek  AirTime  ArrDelay  DepDelay
0  2008     12          22          5     45.0      10.0       6.0

count    1.928371e+06
mean     1.082771e+02
std      6.864261e+01
min      0.000000e+00
25%      5.800000e+01
50%      9.000000e+01
75%      1.370000e+02
max      1.091000e+03
Name: AirTime, dtype: float64

In [69]:
#CAUSES
#-Aquestes basicament especifiquen el motiu i ja son per contrastar amb dades especifiques del vol/temporals
#com p.ex.A: ¿Quina aerolinia te mes cancelacions per LateAircraftDelay? Es que gestionen uns temps massa justos?
#o com p.ex.B: ¿A quins mesos determinat aeroport ha tingut mes desviacions per condicions meteorologiques?